# Generated by Django 4.1.3 on 2022-11-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("description", models.CharField(max_length=128)),
                ("nature", models.CharField(max_length=128)),
            ],
        ),
    ]
