# Generated by Django 4.1.3 on 2022-11-21 16:38
# Generated by Django 4.1.3 on 2022-11-21 16:24

from django.db import migrations


def PopulateTypesTable(app, schema_editor):
    types = [
        {
            "id": 1,
            "description": "Débito",
            "nature": "Entrada",
        },
        {
            "id": 2,
            "description": "Boleto",
            "nature": "Saída",
        },
        {
            "id": 3,
            "description": "Financiamento",
            "nature": "Saída",
        },
        {
            "id": 4,
            "description": "Crédito",
            "nature": "Entrada",
        },
        {
            "id": 5,
            "description": "Recebimento Empréstimo",
            "nature": "Entrada",
        },
        {
            "id": 6,
            "description": "Vendas",
            "nature": "Entrada",
        },
        {
            "id": 7,
            "description": "Recebimento TED",
            "nature": "Entrada",
        },
        {
            "id": 8,
            "description": "Recebimento DOC",
            "nature": "Entrada",
        },
        {
            "id": 9,
            "description": "Aluguel",
            "nature": "Saída",
        },
    ]

    TypeModel = app.get_model("parser", "Type")
    for createType in types:
        TypeModel.objects.create(**createType)


class Migration(migrations.Migration):

    dependencies = [("parser", "0001_initial")]

    operations = [migrations.RunPython(PopulateTypesTable)]
