# Generated by Django 4.1.3 on 2022-11-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0002_auto_20221121_1646"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField()),
                ("cpf", models.CharField(max_length=128)),
                ("cardNum", models.CharField(max_length=128)),
                ("hour", models.TimeField()),
                ("owner", models.CharField(max_length=128)),
                ("store", models.CharField(max_length=128)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transactions",
                        to="parser.type",
                    ),
                ),
            ],
        ),
    ]
